pull_request_rules:
  - name: Merge passing scala-steward PRs
    conditions:
      - author=scala-steward
      - check-success=Travis CI - Pull Request
    actions:
      review:
        type: APPROVE
      merge:
        strict: smart
      delete_head_branch: {}
