language: scala
before_script:
- cd estherj
- pip install --user -r requirements.txt
- python tests.py
- cd ../
script:
- sbt ++$TRAVIS_SCALA_VERSION test
- sbt ++$TRAVIS_SCALA_VERSION "run recipes frontend"
before_deploy: cd frontend
deploy:
  provider: heroku
  skip_cleanup: true
  app: recibase
  api_key:
    secure: R2JZWz7SGvfRLfHPJc2njf0bj7OHEvdhcOLCdtHMhcgSDAiPIe7fH6ZLTyYmOZQ/CuSl7L8C1HQG4NnwsesY9JLV85g1GztA0zyBO2M9KVvWcPJzTsnz/rXyS915EEmLB1rwsO9EKzM+Wm6ugHA/eLs43iE3a3tFwjaRntWxgK1t1QiE8qADPKswe9glRvg5lAJK2ibljMT0op6yhu1FohSpYbJBq5F6tKfS4QojDe3Q/TT2d0DN5ZcW/HsgZYnxxxXbXb2v0f1jA39YVy5yz2fWQ+TOKJJ8/vSZA8TMlxDu2TivyA1WPIa29U4mZEVcfF+CzeQkh/SvvgCW1WAlFG50HLAHmMYNuRh1I13h6JXhScwgJ9S2H09Q7fJ8/xBGx6kUUJRfhDLuG6yms3MxYoQ04c2zZpfNY9HzqL+ptVjCQZZ6SwNae3OMMp9xRcb2hUIZ4aivKO8R7raTmKOt3cnA8kPC9V4i8TQLuNLuifSYV+bb6nC3ZK70IS2+fItuya8zrbAjrsuqnJb2KdpM9sqD8UkusL33oHG3PjYMCfrk/k9MgR7zQMwIph0PrnntcOPeFhdE6/EkRbMeoaYBaFik1q1qrOIOWpqOHbc9amTyKQi/JgT/SWV8+tmhUT/w7QQeAgYRfMKiLc+BzsHmTYSARIgHj3TgsQpJH1mqMLA=
