language: scala
before_script:
- cd estherj
- pip install --user -r requirements.txt
- python tests.py
- cd ../
script:
- sbt ++$TRAVIS_SCALA_VERSION test
- sbt ++$TRAVIS_SCALA_VERSION "run recipes frontend"
before_deploy: cd frontend
deploy:
  provider: heroku
  skip_cleanup: true
  app: recibase
  api_key:
    secure: okYRxwhpBd0L4+QKg/FgoVqavwWX3jKkLabIJdW39hguqtjStN+h8ft4mtzkjYvslfcBgaLq5d10ggtmMnp/u+O/uNubzsmVb9qJdKKl68hxrgF+mxArXEBb/Iif3lejLpyS1cutTPgK6fAtKQ5a+KisJX8mH6nUzWqq0I3It544GQCXRUQJ/quixem+U9f6QjaoQVcZhCy2E09key2tsZRgyUMl8WlTUJTs+wcPm/whIAulVBfwTblQku/eURBXAJb3EfkhrE5ENuH2qgCbUa32Hb4GHDsMPr3PruY47LLn8nuT0qwt4SgCjSgfmU3VsFTMYIrfS6n1wflqFv/i3cLZLFar3NKhy86KZzXaOAcezEcGkgReGLeRZM9w0WMvzIgtWNDncNoTQ3jQPq58ArH5/Bge4AOzz6qpVwyldWfgWvzUfS6vynFPlF41jVUUd6GoZ/yZVT2Mnvk8sfSKdzcyZ7NQmR/W42xLpuwjNdFoKR9D3U4H8SSDH7JXTxZinSnvwRZZgKxeUfw0uhEPosZx73uCZwpzKOai07LgvnB7oTc+GFzVK9mhi/B3TaS4FCglMxUiJd0+sOdzafeuURAH7a+CBJ0YFFZYt4aapIo3FIFMAMo1AuuQYBxRPNDZyOoIBPq/bu4Q2EBvbqGiXKRnEB20CH9Ohfc2UfA+PTg=
