language: scala
before_script:
- cd estherj
- pip install --user -r requirements.txt
- python tests.py
- cd ../
script:
- sbt ++$TRAVIS_SCALA_VERSION test
- sbt ++$TRAVIS_SCALA_VERSION "run recipes frontend"
before_deploy: cd frontend
deploy:
  provider: heroku
  skip_cleanup: true
  app: recibase
  api_key:
    secure: W4chm8bYLP9epaCQiSStff2najjq64yqeG3eBtJFr8NFl+KD972CCdfwV9HdO1iwGAn9xTlvRsKLk7rE8S7VH6AW3RY/m95o7BMR4q9ogK0WUiei2zS1+Lc/O9Qwix3fxMcr6ENXv56vnMovCajBEXpIJo46OOlT7VWjXsSAuyFUyqvOCbgSjHBCxGfeYokQxZPNfTJ5B7cMQKx19ZMYcXvi2VbYvfVHhfKUgZ5ZCJL7+SRZuMNsq3QUZIDh3blkfvUnQe66SYBWZa8y9ZLlb7xdkYYRdx0CFwfQdLqkXQJDBgThkd3V87rBsjkc8HOSC3IhyfteCkAy9ca+RCquLQBLVaDuksG+YRf5VeBM7GkYQ7hUut4Uc++iSfsZTgNiJOrH0uTAcSA6QOrAetAaS8Q7qCUCkv6Y1BjaGIU04eQz+iNYP+SQ+Nwb0XqAlJWFXpk1fW984L0PHsfE+87cyFahsf8c26KaiDGG9+Xikm5pcPeTPWIhZs/P3etL+0IxoR5TgsFcsY1ExkOCTiVmmon0LUJ4yPmKAa7Ud5aoxj2N+Ntdp2GQSyfKZlRI2BcCSXBo/hwXXSiXGi1rB9QLbEIzWYIdHOuHtCoTykGroJ/4unxtroi8vLww5vMMFZix+A4dILvVBGwW0TvjJZDvxrMAgQyoVAQekzj38qwEA2E=
